### ISSUE TITLE
运行html出现以下错误x_x

### ISSUE THREAD

**Issue by wendy515** [DEIT2014/team6exercise#27]
Observatory listening at http://127.0.0.1:51801/
Uncaught Unhandled exception:
NoSuchMethodError: The getter 'readyState' was called on null.
Receiver: null
Tried calling: readyState
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      onDataLoading (http://localhost:63342/team6exercise/web/main.dart:356:15)
#3      _JSObjectBase._callMethod (dart:js:1111)
#4      JsNative.callMethod (dart:js:1455)
#5      Blink_JsNative_DomException.callMethod (dart:_blink:23413)
#6      BlinkXMLHttpRequest.open_Callback_2_ (dart:_blink:23066)
#7      HttpRequest.open (dart:html:21350)
#8      teaReview (http://localhost:63342/team6exercise/web/main.dart:349:11)
  (anonymous function)	
  (anonymous function)

**Comment by meflyup** [comment]
你需要调试，看看你的request是不是null。
